version: '3'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "YtReWq4321"
      MYSQL_DATABASE: "virtd"
      MYSQL_USER: "app"
      MYSQL_PASSWORD: "QwErTy1234"
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build:
      context: .
      dockerfile: Dockerfile.python
    environment:
      DB_HOST: "db"  # Имя сервиса MySQL
      DB_USER: "app"
      DB_PASSWORD: "QwErTy1234"
      DB_NAME: "virtd"
    ports:
      - "5000:5000"
    depends_on:
      - db

volumes:
  mysql_data: